In [10]:
import sys
sys.path.append('..')
from semcable.experiment import Experiment
from semcable.util import make_doc_word_matrix, get_corpus_text

In [14]:
words_of_interest = [
     'swamp', 'trump', 'environment', 'regulations',
     'regulators', 'economy', 'jobs', 'manufacturing', 'immigrant',
     'immigration', 'reform', 'drain', 'attack', 'hit', 'punch', 'clinton',
     'hillary', 'bill', 'donald', 'pelosi', 'ryan', 'paul', 'congress',
     'senate', 'obama', 'washington', 'dc', 'environment', 'epa',
     'lobbyists', 'lobbyist', 'lobbying', 'attacking', 'hitting', 'attacked',
     'lashed', 'punched', 'punching', 'isis', 'iraq', 'peace', 'war',
     'battle', 'fight', 'fought', 'unemployment', 'millenial', 'millenials',
     'vote', 'voting', 'voter', 'fraud', 'tax', 'taxes', 'returns']


In [12]:
texts = get_corpus_text('Three Months for Semantic Network Experiments', 'MSNBCW')
doc_word_mat, vocab = make_doc_word_matrix(texts)

all(word in vocab for word in words_of_interest)

False

In [15]:
[w for w in words_of_interest if w not in vocab]

[]

In [18]:
vocab = ['foo', 'bar', 'baz']

woi = ['bar', 'baz']

vocab_lookup = dict((w, i) for i, w in enumerate(vocab))

woi_idxs = [vocab_lookup[w] for w in woi]

a = np.array([[0, 1, 4], [2, 4, 5], [2, 67, 7]])
print(a)

[[ 0  1  4]
 [ 2  4  5]
 [ 2 67  7]]


In [21]:
a_woi = a[:, woi_idxs]
print(a_woi)

[[ 1  4]
 [ 4  5]
 [67  7]]


In [25]:
woi_indexes = dict((w, i) for i, w in enumerate(woi))

a_woi[:, woi_indexes['baz']]

array([4, 5, 7])